### ISSUE TITLE
Substitution target for io.quarkiverse.logging.cloudwatch.graal.EqualJitterBackoffStrategySubstitutions is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.

### ISSUE THREAD

**Issue by viacheslav-maksimov** [quarkiverse/quarkus-logging-cloudwatch#344]
Quarkus version: 2.14.0-Final
quarkus-logging-cloudwatch version: 5.0.0

I have the following error while building native image: mvn install -Dnative -DskipTests -Dquarkus.native.container-build=true

`[1/7] Initializing...                                                                                    (0,0s @ 0,15GB)
Error: Substitution target for io.quarkiverse.logging.cloudwatch.graal.EqualJitterBackoffStrategySubstitutions is not loaded. Use field 'onlyWith' in the 'TargetClass' annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: Substitution target for io.quarkiverse.logging.cloudwatch.graal.EqualJitterBackoffStrategySubstitutions is not loaded. Use field 'onlyWith' in the 'TargetClass' annotation to make substitution only active when needed.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:72)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1011)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:346)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:324)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:941)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:854)`

**Comment by gwenneg** [comment]
Thanks for reporting this @viacheslav-maksimov!

I'll release a new version of this extension that should fix the issue.

**Comment by gwenneg** [comment]
quarkus-logging-cloudwatch 5.1.0 will be available in Maven Central in a few hours. It should your native build. Don't hesitate to reopen this issue if the problem is not solved by that version.
