### ISSUE TITLE
Logging of percent character

### ISSUE THREAD

**Issue by c-classen** [quarkiverse/quarkus-logging-cloudwatch#457]
The `%` character seems to be handled differently by the default Quarkus standard output logging and this library. This line:

```kotlin
logger.info("Progress: 10%")
```

leads to the following output:

```
2023-08-11 13:19:21,924 INFO  [REDACTED] (Quarkus Main Thread) Progress: 10%
java.util.logging.ErrorManager: 1: Nested handler publication threw an exception
java.util.UnknownFormatConversionException: Conversion = '%'
	at java.base/java.util.Formatter.parse(Formatter.java:2826)
	at java.base/java.util.Formatter.format(Formatter.java:2763)
	at java.base/java.util.Formatter.format(Formatter.java:2717)
	at java.base/java.lang.String.format(String.java:4155)
	at io.quarkiverse.logging.cloudwatch.LoggingCloudWatchHandler.publish(LoggingCloudWatchHandler.java:82)
	at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:327)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	at org.slf4j.impl.Slf4jLogger.log(Slf4jLogger.java:574)
	at org.slf4j.impl.Slf4jLogger.info(Slf4jLogger.java:288)
	[REDACTED]
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
```

While the line is logged as requested by Quarkus, it is not sent to Cloudwatch. Instead, an exception is printed to standard out.

Considering Log4Shell, I'd probably prefer if the string I pass to the logging functions was printed without any processing. However, if some sort of conversion is enabled, it would be nice if it was documented and the error message and stack trace should also be sent to Cloudwatch, so people relying on that log know that there was some logging that failed.

**Comment by bennetelli** [comment]
@c-classen I just pushed a fix for your problem and will release it now. It should work updating after your quarkus logging cloudwatch dependency. Much thanks for raising this issue :)

**Comment by bennetelli** [comment]
Hey @c-classen I just released 6.6.0. It should be fixed with this version. Please let me know if it works for you.

**Comment by vkrizan** [comment]
@bennetelli which commits were fixing the issue? We need to backport them to version 5 to support Quarkus 2. Thanks.

**Comment by vkrizan** [comment]
@gwenneg @josejulio can you please help with this? Thank you!

**Comment by bennetelli** [comment]
It's part of the commit with revision number 02b4305138a2395f61e95d22c7506047d67528d3 and two commits later (revision c5a8ea99e2e50f372d144c46a55e796e8786eb42) I also fixed some formatting issues coming from quarkiverse restrictions. So I guess you just want to pick the one containing the fix only? 02b4305138a2395f61e95d22c7506047d67528d3

**Comment by vkrizan** [comment]
@bennetelli if those later commits are related and required, can you please also include them as well? Thank you!

PS: I'd recommend to branch out the version 5 and open PR with the cherry-picks against it.
